# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Seito Kasai
title: MS Student, Computer Science and Electronic Engineering
email: skasai@aoki-medialab.jp
website: https://skasai5296.github.io/

# Social links
twitter_username: sk_gnkr96
github_username: skasai5296
# dribbble_username: jekyll
facebook_username: seito.kasai
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: seito-kasai-9541b1182
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  My name is Seito, and I study computer vision & machine learning.
  I'm currently a MS student working on vision & language at Aoki Media Sensing Lab. in Keio University, and live in Tokyo, Japan.
  Although I used to code mainly for my research, my recent interests are creating software to give an impact on many people.

  Currently I am looking for engineering/research internships, especially ones in which I can express and enhance my coding skills.
  If you're interested, please don't hesitate to contact me!

  Programming Languages: <mark>Python</mark>, <mark>C/C++</mark>, <mark>R</mark>, <mark>MATLAB</mark>, <mark>Java</mark>

  Skills: <mark>Machine Learning</mark>, <mark>Computer Vision</mark>, <mark>Natural Language Processing</mark>, <mark>Data Science</mark>


# Projects Section
projects_title: Projects

# Experience Section
experience_title: Work Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  I used to live in Miami, FL in the U.S. for about 6 years when I was young, so I'm comfortable communicating in both Japanese and English.
  Alongside my interests in machine learning research and software engineering some of my other interests and hobbies are:
   - Playing Tennis (I've played for more than 15 years!)
   - Travelling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-slate
