# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Seito Kasai
title: MS Student, Computer Science and Electronic Engineering
email: skasai@aoki-medialab.jp
website: https://skasai5296.github.io/

# Social links
twitter_username: sk_gnkr96
github_username:  skasai5296
# dribbble_username: jekyll
facebook_username: seito.kasai
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: seito-kasai-9541b1182
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi! My name's Seito, and I study computer vision & machine learning. I'm currently a MS student working on vision & language at Aoki Media Lab. in Keio University.
  Although I used to code mainly for my research, my recent interests are creating software to give an impact on many people.

  I am most skilled in: <mark>Python</mark>, <mark>Computer Vision</mark>, and <mark>Machine Learning</mark>


# Projects Section
projects_title: Projects

# Experience Section
experience_title: Work Experience

# Education Section
educaton_title: Education

# Publications Section
publications_title: Publications #(Use this to override about projects section title)
publications_content: |
  ## <b>Journal</b>
  * (Under Review)
  ## <b>International Conferences</b>
  * N. Akimoto, <b>S. Kasai</b>, M. Hayashi, Y. Aoki, 360-DEGREE IMAGE COMPLETION BY TWO-STAGE CONDITIONAL GANS,
    IEEE International Conference on Image Processing (ICIP), Sep 2019.
  * K. Yoshida, K. Okayasu, K. Tsubura, M. Minoguchi, T. Ikeya, A. Nakamura, <b>S. Kasai</b>, H. Kataoka, Which generates better jokes, hand-crafted features or deep features,
    CVPR 2019 Language & Vision Workshop, Jun 2019.
  ## <b>Domestic Conferences</b>
  * <b>笠井誠斗</b>，林昌希，秋本直郁，青木義満，自然言語指示文を用いた顔画像属性変換，動的画像処理実利用化ワークショップ (DIA), OS5-3，2019年3月
  * <b>笠井誠斗</b>，中込優，黒澤郁音，矢代達希，西川真史，相澤宏旭，福井宏，【招待ショートサーベイ】コンピュータビジョンと自然言語処理の共存マップ，
    電子情報通信学会，パターン認識・メディア理解研究会(PRMU)，2018年10月
  * <b>S. Kasai</b>, Y. Ishikawa, T. Wakamiya, K. Hara, H. Kataoka, Exploring the Best Model for Dense Captioning Events in Videos, 
    The 22nd Meeting on Image Recognition and Understanding (MIRU), Aug 2019.

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in machine learning research and software engineering some of my other interests and hobbies are:
   - Playing Tennis
   - Travelling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-slate
